sudo: false
language: python
python:
- '2.7'
- '3.6'
install:
- pip install -r requirements.txt
script:
- pylint mongo setup.py
deploy:
  provider: pypi
  user: leonsp@ca.ibm.com
  password:
    secure: 0QWok+FqmPnaJU1B/3eid4IdI2uvpClm3X3BsyfclUuuAU2OQvti9NvLe1Wb63RtfY9BWhrIK9c8OuZCqLoGSy7Ftju2TdPh7bEaRw1DDAT+5+L89u5b1ynBz+pxYQo8GPzFtEai0Vx9YQ1u809d9oSqGioD/tHeE4Wmc60vqjpQoSix0aM9NTq+H8LrP/DhgmWgT0j6tP8oW/sgMqsFexVAuquT2J1GS1xL2KG6yPWnfTBiDne/40wsdhjUTpJo5WMpkJRjNO/HeDJPRJibAVYQray8Go66nJBcjN/lJdEz1X0He8tl2j8VP3yo1iFZ0PSMuotio4Xafg2Y0OZ0rvAlSq0dyqw2zYC5rW6TksNJ0gSoyjVynMyPpKCaaiMtWZ+zKbBKMEqnE/O0wPRLtfXQUwNds/aUK+/B2UHQDRkFOpn7e8aY3LNZXTdhzyBSaNthUIbaxC8+UH5+wRCuRoippy9u7Ka0dUimT+OTPAquXthaLR/7pZBlOVgHo6OO8kMruTwinHKedISepV6M2oeAjHHOthC6uGuEdKIEtaXpHY0aCU0KIoYUKpDgwwydtCJTDfQHOMomBOvgWZZQSyz37jig5AugSbg/1HDPfxs4tUyF6LvtzHB7z8pf4tYrD+FAhJls3Ni/IxJmovw8ZCF8wOkDbJ2vegIkb6i/xCg=
  server: https://na.artifactory.swg-devops.com/artifactory/api/pypi/apset-pypi-local
  on:
    python: '2.7'
    repo: apset/monsoon-backup-mongo
    tags: true
notifications:
  slack:
    secure: Tw/4p3ldNXIVHWT31d1juvoT8m3OW/yl0c5ZtqrjeVoFN2I0GM0aMOng9mHM6Fgaxm0OxjHR8MVDRKuqaslGUpxX6PzrzH6AhN4+kZSKTCLD1DhUg4PElJVIDIfYF+shi9L1wizrg1VjTwZMslpSSrHWwGKYhitBoLKyzKgqFg0rjpyed/X8p7WWH+OciDFeh5cWwYA/7Y9HSfnvkh4PMkssXWsiiv+ed3wHEgsD/PkraJQartwA6ZFvETjScUej1ll+FDu2T2VC0dh9yfiDr3oXtGPDOHcEKgbfnIROtYozx10KYgPNVYEKiIcSssjvZ/WHc6TdTYiSBNkGrZipG3iWf/hxAN1CC6L4na16yKLqDolM6936qiZTgztL/xPMYyUPFmz4ZQmUv4KZOoXlXDmrITBP5plUZvyNRnr3LTv5T2jIl+ynKSihfV+KfiZ4m9CEeUdZRpoVmOspjE40bgNlQHm8njm6oCZDYFHb92JqR74Qw3Sc/YeJSDAmbpThU+/hG4y8DaiIZndSpluiFdDpwbiglDkHxAc0Gu+1oVFfEDXi85FpkHqGRp2zyltjdnPuHCNQzNHYovrVRjC+t0OQxpxa9VcSvPbLya6JKldSe5mnEJqoyLTCu7vvHZXbc1TRAQcWefnzPcwUhwU/BWs9y2/c84VoIgAr4hOKn6Q=
